In [1]:
import numpy as np
from itertools import combinations, product

In [3]:
r=3

# Параметры кода Хэмминга

 $r$ — количество проверочных символов (ранг проверочной матрицы)

## Основные параметры

### Длина кода
$$n = 2^r - 1$$

### Количество информационных символов
$$k = n - r = 2^r - 1 - r$$

### Скорость кода
$$R = \frac{k}{n} = \frac{2^r - 1 - r}{2^r - 1}$$

### Минимальное расстояние
Для кодов Хэмминга минимальное расстояние всегда равно 3:

$$d_{\min} = 3$$

### Корректирующая способность
Код гарантированно исправляет:

$$t = \left\lfloor \frac{d_{\min} - 1}{2} \right\rfloor = \left\lfloor \frac{3 - 1}{2} \right\rfloor = 1$$
одну ошибку.



In [6]:
# вычисляем n и r
n = 2**r - 1
k = n - r

print("Длина кода (n): ", n)
print("Количесвто ИС (k): ", k)

Длина кода (n):  7
Количесвто ИС (k):  4


## Построение проверочной матрицы $H$ размера $r \times n$

### 1. Формирование столбцов матрицы $H$

Столбцы матрицы $H$ — все ненулевые двоичные векторы длины $r$.

Для $i = 1$ до $2^r - 1$:
- Преобразовать число $i$ в двоичное представление длины $r$
- Полученный вектор использовать как строку матрицы


### 2. Транспонирование

Полученная матрица имеет размер $n \times r$  
Выполняем транспонирование, чтобы получить матрицу $H$ размера $r \times n$:



In [9]:
# Строим проверочную матрицу H размера r x n
# Столбцы H - все ненулевые двоичные векторы длины r - двоичнные представления числа i длины r
H = []
for i in range(1, 2**r):
    # Двоичное представление числа i
    binary = format(i, f'0{r}b')
    col = [int(bit) for bit in binary]
    H.append(col)
    
# Транспонируем, чтобы получить матрицу r x n
H = np.array(H).T
    


# Построение дуального кода
Дуальный код к данному линейному коду — это код, порождающая матрица которого является проверочной матрицей исходного кода.

Т.е еслу у кода проверочная матрица $H_{Хэмминга}$.

Тогда у дуального к нему кода порождающая матрица:

$$G = H_{хэмминга}$$

(если исходный код является $(n, k)$-кодом, то дуальный код является $(n, n-k)$-кодом)

In [12]:
G=H
print("G_{Дуального}")
print(G)

k, n = G.shape
print("Параметры дуального кода:")
print("Длина кода (n): ", n)
print("Количесвто ИС (k): ", k)

G_{Дуального}
[[0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1]]
Параметры дуального кода:
Длина кода (n):  7
Количесвто ИС (k):  3


# Симплексный код



1. Все ненулевые кодовые слова симплексного кода имеют одинаковый вес Хэмминга:

$$ d(x_i, 0) = w(x_i) = w(x_j),\quad \forall {x}_i, {x}_j \neq \mathbf{0}$$

2. Расстояние Хэмминга между любыми двумя различными кодовыми словами одинаково:

$$ d(x_i, x_j) = const, \quad \forall {x}_i, {x}_j$$


In [15]:
codewords = []
    
# Генерируем все возможные информационные векторы и смотрим на их вес
    
print("КС | вес")
for i in range(2**k):
    # Двоичное представление числа i длины k - ИС
    info = np.array([int(bit) for bit in format(i, f'0{k}b')])
    # Кодовое слово = info * G mod 2
    codeword = np.dot(info, G) % 2
    print(codeword, " ", np.sum(codeword))
    codewords.append(codeword)


КС | вес
[0 0 0 0 0 0 0]   0
[1 0 1 0 1 0 1]   4
[0 1 1 0 0 1 1]   4
[1 1 0 0 1 1 0]   4
[0 0 0 1 1 1 1]   4
[1 0 1 1 0 1 0]   4
[0 1 1 1 1 0 0]   4
[1 1 0 1 0 0 1]   4


In [17]:
# проверяем, что 
num_codewords = len(codewords)
distances = []
for i in range(num_codewords):
    for j in range(i + 1, num_codewords):
        dist = np.sum(codewords[i] != codewords[j])
        print("d(",codewords[i],"," ,codewords[j], ")=", dist)
        distances.append(dist)
   
unique_distances = np.unique(distances)

d( [0 0 0 0 0 0 0] , [1 0 1 0 1 0 1] )= 4
d( [0 0 0 0 0 0 0] , [0 1 1 0 0 1 1] )= 4
d( [0 0 0 0 0 0 0] , [1 1 0 0 1 1 0] )= 4
d( [0 0 0 0 0 0 0] , [0 0 0 1 1 1 1] )= 4
d( [0 0 0 0 0 0 0] , [1 0 1 1 0 1 0] )= 4
d( [0 0 0 0 0 0 0] , [0 1 1 1 1 0 0] )= 4
d( [0 0 0 0 0 0 0] , [1 1 0 1 0 0 1] )= 4
d( [1 0 1 0 1 0 1] , [0 1 1 0 0 1 1] )= 4
d( [1 0 1 0 1 0 1] , [1 1 0 0 1 1 0] )= 4
d( [1 0 1 0 1 0 1] , [0 0 0 1 1 1 1] )= 4
d( [1 0 1 0 1 0 1] , [1 0 1 1 0 1 0] )= 4
d( [1 0 1 0 1 0 1] , [0 1 1 1 1 0 0] )= 4
d( [1 0 1 0 1 0 1] , [1 1 0 1 0 0 1] )= 4
d( [0 1 1 0 0 1 1] , [1 1 0 0 1 1 0] )= 4
d( [0 1 1 0 0 1 1] , [0 0 0 1 1 1 1] )= 4
d( [0 1 1 0 0 1 1] , [1 0 1 1 0 1 0] )= 4
d( [0 1 1 0 0 1 1] , [0 1 1 1 1 0 0] )= 4
d( [0 1 1 0 0 1 1] , [1 1 0 1 0 0 1] )= 4
d( [1 1 0 0 1 1 0] , [0 0 0 1 1 1 1] )= 4
d( [1 1 0 0 1 1 0] , [1 0 1 1 0 1 0] )= 4
d( [1 1 0 0 1 1 0] , [0 1 1 1 1 0 0] )= 4
d( [1 1 0 0 1 1 0] , [1 1 0 1 0 0 1] )= 4
d( [0 0 0 1 1 1 1] , [1 0 1 1 0 1 0] )= 4
d( [0 0 0 1 1 1 1] , [0 1 1 1 1 0 